CREATE TABLE IF NOT EXISTS posts(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100),
	description VARCHAR(900),
	creator_id INTEGER,
	likes INTEGER DEFAULT 0,
	image_name VARCHAR(300),
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);